dataset_0 = [
	"CGGTGGGCTACCGCTAGTATAAGGTGGA",
	"CGGTGGGTTACCTCGATTATAAGGTCGA",
	"CGGGTCGGTCATCCCTAGTTATAAGGTCGA",
	"CGGTGGGTTACTGCTAGTATAGGGCTGT"
]

dataset_1 = [
	"CTTGCCGGGGGACTTGTGTCGCCGAGGGCA",
	"CTTGCGGGGGAGATTGTGGGGTTATCTGCA",
	"CTGGCCGGCGAGATTGTTGCGCGGTGCA",
	"CTTGCCGGGCAGATTGTGGCGCTCGCCA"
]

dataset_2 = [
	"GAACGCGCCAATGGCATTGGAACCTA",
	"GCAACGACCCCCATGTCATTGGGAGACCCA",
	"GCAACGACCCCAATGTCATTGGAAACCCG",
	"GCCACGACCCCCATGTCATTGGTAACCCA"
]

dataset_3 = [
	"TTGGCCCCGGAAGACCGCTTCTTGCGTGA",
	"TTGAGCCCCGAAGACCGCTCTTGCGGA",
	"TTAGCCCCGAAGGCCGCGTCCTTGCCTA",
	"TGAGCCGAAGACCGCTTCTGCCGC"
]

dataset_4 = [
	"CTAAAATCTTCAGCGTAAGGTACC",
	"CTAAAATCGTCCAGCCTAATTACC",
	"CTATAATCTCCGCCTGATGTACC",
	"CTAAAATCTCCAGCTAATGTACG"
]

dataset_5 = [
	"AACGTTTAGCCCTTACAGCGCGCTAGC",
	"TAAGGTCTTAGGTCCTTTCCGTTGCGTCTAGC",
	"AAGGTTCTAGCTCCTTTCAGCGGCGTCTAGGC",
	"AAGGTCCTAGCCTCCTTACAGCGCGTCTACC"
]

dataset_6 = [
	"TTTCCCTCCTCATTCCTAACTCGTCCAGAA",
	"TTTGCCCCCTCAGCCTAAGTGTCCAGAA",
	"TTTGCCCCTTCACCTAACTTGTCCGAA",
	"TTTGCCCTCCGCAACTTAACTGCTAGAA"
]

dataset_7 = [
	"TAGTTGGAAATTCGGGGTTGAAGG",
	"TAGTCTGGGAACTTCGGGGTCGAAGCG",
	"ATAGTTGGACCTTCGGGGTTGAAGG",
	"ATAGTTGGCAATTCGTGGTTTGACGG"
]

dataset_8 = [
	"TAAGTGGGTCACCCTATTAATG",
	"TAAGTGGATCCGCTTATTACG",
	"TGTGGTTCACTTGATAGAG",
	"TAAGTGGACCCCATTAAG"
]

dataset_9 = [
	"TCACGGTTCCATACGCCTGATAA",
	"GCATGGGTTCATACGCGATAA",
	"GCACGTTTCATGGGCCGTCGCAA",
	"GTACGGTTCATGCGCCGATAA"
]

dataset_10 = [
	"CGAGCAATGTAAGAAAAGAGG",
	"CGAGCAATGTAAGATAAAAGG",
	"GAGCAATTAAGATATATG",
	"CGAGCAACGAAGGAAAAAGG"
]

dataset_11 = [
	"GCCCTGGAAGTGCTTCACGCTTAACATCCT",
	"GCACTGGAATGCTTCACGTTGCAACACCCC",
	"GTCACCTGGAATGTTCACTTCGAACGTTCCG",
	"GCCTGGAATGCTTCACCCTTGAACATCCT"
]

dataset_12 = [
	"AGGCCGTGTCCGCATGCCTCGCTAGGTA",
	"AGGCCGTGTACGAACCCTCTCTGGGGTA",
	"ACTGCCGTGTACAATCTTGCTGAGGTA",
	"TGGGCCGTGTACGAGTCCTCGCTCAGGTA"
]

dataset_13 = [
	"GACCTACAGTATGCTCGGATATGATTGA",
	"GTACTACACTCAGCTGTGTATTAGTATGA",
	"GCAGCTACACTTAATTCTCTGGGATAAGATGA",
	"GTACTACCTACTTTTCCTGGATAAGATGG"
]

dataset_14 = [
	"ACTATGGCATGAGGCCGATACCCGGA",
	"ACTAATGGCATGGCCGATGCCCGGA",
	"ACTAATCGGCATGATGGCCGATACCCGGC",
	"GTTAATGGCATGAGCGCCGATGAGCGGA"
]

dataset_15 = [
	"TAAGAGTCCCAAGGCTGTCGTAGCTTTC",
	"TAAGGGTCCCAAGGCTGTGTAGGTGTT",
	"TAACGAGGTCCCACAGGCTCTGTAGCTCGTT",
	"TAAGAGTCCCCCAGGCTGTCTAGCTTT"
]

dataset_16 = [
	"CGTTAGCACAGCGGCTTTGTCGG",
	"CGGACGGCCAGTCCTTCGGATGGG",
	"CGTATAGGACAGTCCTTTGATCGG",
	"CGTAAGGACAGCCCTTTGATCCGG"
]

dataset_17 = [
	"ACTGCGGGCGCCTACAGGGCCGA",
	"CACGTGTTGCGCCTGCAGGTCTGA",
	"ACGTGTTGCCCTACAGGTCTGA",
	"ATGTGTTGCGCCTAGACGGGCTGA"
]

dataset_18 = [
	"TAGCTTGCGCTGTGAGCCCTGGTCA",
	"AGAGCTTTCCTTACCCCTGGGCA",
	"AGTCTTGCCTTAGCCCCTGGCA",
	"AGCTTGCCTTAGCGCCTCGCA"
]

dataset_19 = [
	"ACTACAGGTCAGCGTAGCATCCTCACT",
	"ACTACAGTGTCCAGCGTGCATCATCACC",
	"ACTTACAGGGTCAGCGTAGCATCATCACT",
	"ATTACAGGTCAGCGTAGCATCATCACT"
]

dataset_20 = [
	"TTAGGTATCCAGTATGGCTTTAAACGC",
	"TGCTTAGGTACCCCGTTATGCTTTAGAGC",
	"TGTTAGGTATGCCAGTCATTGACTTTAAAGC",
	"TGTTGGGTATCCAGTGATTACTTTAAACGC"
]

dataset_21 = [
	"GCTGCCAGGGGCAAACCGCCT",
	"GTTGCAGGGAACAAACTCCCT",
	"TTGCAGTGGAAAAACTCACT",
	"GCTGCAGTAACGAAGTCACT"
]

dataset_22 = [
	"GCCGTTTCACGCCGTCGTTTGT",
	"CTGTTGTCACGCACCGTTTGTT",
	"CTGTTTCAGGCGCCTTTGTT",
	"CCGTGTCACGCAGGTTTGTT"
]

dataset_23 = [
	"ACCGCTGCCCAACGACTGTCACGGGCGAG",
	"GCGCGCCCAAGACACGACGGCGAG",
	"GGCGCGCCCATGATTCTCACGGCGAG",
	"AGCGCGGCCAATCGCCTATAGGCGTG"
]

dataset_24 = [
	"TTGACGATTAAGGACTGAGGCGATGA",
	"TTGACGATGAAGAGACCGAGACGAGTA",
	"TTGACGATGACGGACACTCGAGGAGTTGA",
	"TTGACGATTAAGAGCTCGAGAATGAGTGA"
]

dataset_25 = [
	"AGGAGTCGATACACATCGACGAT",
	"AGGATACGATCCACATGATGTAT",
	"AGGATACTATTCACATCGATGTAT",
	"AGGATACGATCGATCGATGTT"
]

dataset_26 = [
	"AAGTGCTGGGTCGTCTGA",
	"AGACGCCTGGGTTCTCGGA",
	"GACGCCTGGGTGCCTCTGA",
	"AGACGCCGTGGCTTCGTTCGA"
]

dataset_27 = [
	"TCAGACAAGCTGGAAACGCAC",
	"TCAGACGAAGCGTGGAACTCAT",
	"TCAGATGAAGCCTGGAAACTCAT",
	"TCAGACGAAGCTTGGTAGTCACT"
]

dataset_28 = [
	"ATAAGTACCTGCAAATGGAGA",
	"AGCAAGTACGGTGATATGGAGCA",
	"TAGCATAGGACGCGTGAAATGGAGA",
	"GCAAGTAGTTTGCTAGTGGAGA"
]

dataset_29 = [
	"ATTTCATACCAGCTGGGGC",
	"AGTCATATCCCAGCTGGGGA",
	"ACGTCATACCCAGCTGTGGA",
	"ACGCATACTCAGCTGGGA"
]

dataset_30 = [
	"TGTCCACACAACGCCTTTGTCGCTTTTA",
	"TGGATCACACAACGCGTTTTCCGCGGTTTTA",
	"CTGTATCACACAACGCCTGTCCCCTTGTTA",
	"TGTACTGCACACACGCCTTTTCGGTTTTA"
]

dataset_31 = [
	"CCTGCACTCTCCGGAGGGGCA",
	"CCTGCACTGGCGGTACCGGCTA",
	"CCTGCATGTCGGAGGGGCA",
	"CTCTGCACGGTCGGAGGGCA"
]

dataset_32 = [
	"TGCGAATCGGCTAGGATAATGA",
	"TGCGAATTGGCTGTAGGATAACGA",
	"TGCGAATTTTCTGGAAATGA",
	"TGCGAATTGGGGTAGCTATAAGGA"
]

dataset_33 = [
	"GACTAATTACTAGGCCGCACGAGGGT",
	"GACGAATTCTAGGCGTCACGAGGATT",
	"GACGAAGTACCTAGGCGCACGAGGATT",
	"CGGACGAATTACTAGGCGCACGAGGATT"
]

dataset_34 = [
	"AACTTTTCCGCTATGCGGTGTTTGC",
	"CTTTTACCCGCTTTCGGCGC",
	"AACTTTTACCCTCCTATGCGTGTGAGC",
	"ATCTTTGACCCGCTATGCGTGTGAGC"
]

dataset_35 = [
	"TAGGAATTCTGAGTGTCCAATTGG",
	"TAGGAAGTCTGAGTGTCAATTG",
	"TAGGAAGTCTGAGTGTCCAATTG",
	"TTAGGAAGTCCGAGTGTTCATACTTG"
]

dataset_36 = [
	"TAGGCGTGTTATAGTCGTCAGTAATG",
	"TAGACGTCTATAGTACGTTGGATG",
	"TACAGACGTTATAGTAGCGTAGCTAATG",
	"TAACCGAGTTATGGTACGTAGTAGTG"
]

dataset_37 = [
	"CCGATATTACGTTTGATTTTGTTCTCC",
	"GCGGCCTCGTTTGATTTTGCTC",
	"GCATATTACGTTTGATTTTGTCTC",
	"GCGTATGACGTTTGATTTTGTTCCC"
]

dataset_38 = [
	"ACGACCTTGTGCTAACCGAAGTGCA",
	"ACGCCCTCTGTGCCAACTGAAGTGCA",
	"ACGCCCTTGTGCTAACTGTAAGTGCCA",
	"ACGACCTTGTGCTAACTGAATCCA"
]

dataset_39 = [
	"CGCGTATGGTCGCCGTCTACATACGA",
	"CGCCTATTTGCTGTTACATCA",
	"CGCCTATTTGCTGTTCATACGA",
	"CGCCTATTTGGCTGTTACATACGA"
]

dataset_40 = [
	"AGCTGCCCTAAAGCATCAGTGTTTTCGGG",
	"AGCGCCCTAACGGCAAGTGTTTCGG",
	"AGCCGCCCTAACACCGAAAGGGGTTCGG",
	"AGCCGCCCTAGCCGCAAAGTGTTTCGG"
]

dataset_41 = [
	"TTCTCGCGCTTTGATCCTGCAT",
	"GTTTCGATCCTTGGATCTGTCATA",
	"GTCTCGATCCTTTATCTGCAA",
	"GTCTCGATCCTTTATCTGCCA"
]

dataset_42 = [
	"CCTTTCCGAGGCACAGTATCCAACCCTC",
	"CCTTTCGACGCACAGTATCCTAACTCGG",
	"CCTTTCCGACGCACAGTATCCAGCTCGC",
	"CTTCTTTCCGTACGCACAGTCCAACTTCCC"
]

dataset_43 = [
	"TGCAGCGCTTGTCCAACTCTGCGTTAT",
	"TGCAGCGCGTCTAACTCGGCTTTAT",
	"CTGCAGCGTGTCCAACTCTGCTTGT",
	"TGCAGCGTGTCCTACTCGGCTT"
]

dataset_44 = [
	"GTTATGCTCCAGGATGGAACT",
	"TTTAGGTCCAGGATAGTACT",
	"GTTAGCTCCACGATAGAAT",
	"GTTACGTCTCCAGGATAGCACT"
]

dataset_45 = [
	"TACATTGTGCCATGTTGGGTGCAATTC",
	"CACATTCTGCCATTTGGCTGCAACTCC",
	"CATATTCTGCCTTTTTGGCTGCATTC",
	"CACCTTCTGCCTTTTTTGCCTGGACTTC"
]

dataset_46 = [
	"AGCGGCGCTACGGGGCGATAGTTCGCC",
	"AGCGGGCGCTACGGGCGATAGTTGGCC",
	"AGGGTGCGCTAGGGCGTTAGTTCGCG",
	"AGCGGCGCTCGTCCGATAGTTTGCC"
]

dataset_47 = [
	"TGAAGCTAATAACGCTCGCTTCAGTTATGG",
	"CGAAGTTAATAACGGCGTGTTGACTTAGGG",
	"CGAGCTAATAACTGTTCGGGTGTGACTTAGTGG",
	"CCGCAGCTAATAACGCGTGTCGACGTATGG"
]

dataset_48 = [
	"GTGTAGCACCGCGAGGATTTCGTGCTGTTC",
	"GTGTAGCACTGGCCAGCGATTTCGTGCCGTTC",
	"GTGTAGCACCGCCTGGATTTCGTGCCGTCTGC",
	"GTGTATCCCCGCCAGGATTCGCGCGCGTTC"
]

dataset_49 = [
	"TACTTCTCATTGGTGCACGTGGTGCCTG",
	"TACTTCGTCATTGGGCGCACCTTGTGCCTG",
	"TATTCTCCATTCGGGCACGTTGTGCTTG",
	"TACTTCCAGCTGGGGCCCGTTGTCCTG"
]

datasets = [
	"dataset_0",
	"dataset_1",
	"dataset_2",
	"dataset_3",
	"dataset_4",
	"dataset_5",
	"dataset_6",
	"dataset_7",
	"dataset_8",
	"dataset_9",
	"dataset_10",
	"dataset_11",
	"dataset_12",
	"dataset_13",
	"dataset_14",
	"dataset_15",
	"dataset_16",
	"dataset_17",
	"dataset_18",
	"dataset_19",
	"dataset_20",
	"dataset_21",
	"dataset_22",
	"dataset_23",
	"dataset_24",
	"dataset_25",
	"dataset_26",
	"dataset_27",
	"dataset_28",
	"dataset_29",
	"dataset_30",
	"dataset_31",
	"dataset_32",
	"dataset_33",
	"dataset_34",
	"dataset_35",
	"dataset_36",
	"dataset_37",
	"dataset_38",
	"dataset_39",
	"dataset_40",
	"dataset_41",
	"dataset_42",
	"dataset_43",
	"dataset_44",
	"dataset_45",
	"dataset_46",
	"dataset_47",
	"dataset_48",
	"dataset_49",
]

file_name = "dataset4"
