dataset_0 = [
	"TACTAATTGGACATTTACGCTA",
	"AGTCAATTGGACTTTTATGCTCT",
	"TAGTCAATTCGACATGTATGTTA"
]

dataset_1 = [
	"GGTACTTTGATCCTCAGTACCC",
	"TGTGCTTTGTATCCTTCAGTTCCTC",
	"GTACTTTGATCTCCTCAGTGCCC"
]

dataset_2 = [
	"AGGCCTCGTATATTCCGATACGGA",
	"AGGCCTCGTTTATCCTCCGATGCTGA",
	"AGGCCCGTATATTTCCATTCTGA"
]

dataset_3 = [
	"GTTCTGCCATTCTGCCACTATAACGCATGA",
	"GATTCGCCTTATCTGCCACTCTAAGGAGGA",
	"GGTCGCCGTATCTGCACTATAAAGGGCA"
]

dataset_4 = [
	"GGGGCCCTTGGCATCCCAGTTGTTGC",
	"GGGGCCCGTGGCTATCCGCCAGTGTTAC",
	"GGGGCCCGTGGCTTAGCCCGCAGTTTAG"
]

dataset_5 = [
	"TCAAGTTCATGTCCACTTCAGTAACACAA",
	"ACAAGTTCATGTCACTCTGCAGTAACACAC",
	"ACAATTCAGTCCGACTTCCAGTAACAGAA"
]

dataset_6 = [
	"TTTCTAGGATGTACCGCAGA",
	"TTTCTAATATGTACCTGCAGA",
	"TTTCTAGATGTATCCTGATA"
]

dataset_7 = [
	"GCCAGCCCTGCCCCTACTGCAGCCCTA",
	"GCCACTCCTGCCCCCTATGCAGACACTA",
	"GTATGGCCTGCCCCTATGCCAGACCCTG"
]

dataset_8 = [
	"CTACTCTCGTACACCTTGA",
	"TGTAATCCTCGTTACACCTTGA",
	"TCAACTCTCGTGCACCGTGG"
]

dataset_9 = [
	"AACCCAGCCTAGATTTGCGCAGGA",
	"AAGCGTCCAGGTTTTCGCAGGA",
	"AACCAGTCCAGATTTGGGCGGGA"
]

dataset_10 = [
	"GCTATGCCGCGTATGGCAAGAC",
	"CTATGCCCGTTATGGCAAGAC",
	"CACGCCGTGTATGGCAAGAC"
]

dataset_11 = [
	"CCGGATAGGTTTATTTAGTA",
	"ACGATTGTGTTCTTATTCAGTA",
	"ACGGATATGTTTTATTCATTA"
]

dataset_12 = [
	"CTTCCGAAGGTACAGCGCTTTTTCACTA",
	"TGCCTTAGGTACTAGCGCTTTTGCTCAGGA",
	"TCCCTCACGTACGCGCTTCCTCAGA"
]

dataset_13 = [
	"ATTTGGAAATGCCCGGGGTGGTTGCCTA",
	"ATTTGTAAGATGCCCGGGGTGGCTGCCTA",
	"ATTGTCGTAAGATGCCGGGGTGGTGCCTA"
]

dataset_14 = [
	"ACCGCGCTATAAAGAATC",
	"ACTGGGCATATAATAATCT",
	"ACTGGCGCTATAAATAAGTTCT"
]

dataset_15 = [
	"AATTGTTTGCGACGACTTT",
	"GATTTTGCCGCGAGCGACTTTCA",
	"ATATTTCGTCCGGGACGACTTA"
]

dataset_16 = [
	"GTGGGTGTTCGCATTTAGGGAAT",
	"CGTGGGTGTTCGCATTTAGGAAA",
	"GTGGGTGTTGGCATTTAGGGAAA"
]

dataset_17 = [
	"AGTAACTCGCTGTACTCCGACTATGG",
	"AGGAACTGGCTGGACTACCGTGTATCG",
	"ACGAACTGGCTGCACTACCGACTATCG"
]

dataset_18 = [
	"TCCGTCGTCCCTATCAAAAAGATGTCCT",
	"TGTACTCTCCTAGAAAGAGTTATCCA",
	"GGCATCATTCTCTTACAAAAAGATTATCCA"
]

dataset_19 = [
	"TATATACATGGATAATTTCGCCTT",
	"TACATACATGGAGATTTCGCCTT",
	"TACATAATCGGATAATTTCGCCTT"
]

dataset_20 = [
	"GCCTTTGCCATATGGTATCACCCTGGGC",
	"GGCTTTGCGAATGGTATCACCTCTGGGT",
	"GCCTTTGCGAAGGGGTATCACCCCTGG"
]

dataset_21 = [
	"ATTTCGGGCATTGCGTGAACGGATTCG",
	"ATCTCGGAACTCGCGAACCGATTGTCG",
	"GATTTCGAGTCTCGTGAACCGGTTGTCG"
]

dataset_22 = [
	"TATTGTACCCCTATTGTGCGCCAGTATAGTC",
	"TTCTGTACCCATTGGTGTGCCAGTATAGTC",
	"TATTGTCCCTTGTGGGGGAGTCTATTC"
]

dataset_23 = [
	"CCCGTCTATACTGGGCTCGCTGTTGTTC",
	"CCCGGCAACTGCGCCTCGCTGTTGGATC",
	"CCCGTTAATACTGGACTCGCTTTCGATC"
]

dataset_24 = [
	"GTGTTCTCGAGTTCCGCCCTACGTT",
	"GTCACTCGGAGGTTCCGCCCTACGTG",
	"GTGGACCCGCGTTCCGCCCTACGTT"
]

dataset_25 = [
	"AGCTAGAAGTCAGCCGCGCCTC",
	"AGCGAGAATGTCGAGCAGCGCCC",
	"AGCGGCATACGTCAGCTGCGCCT"
]

dataset_26 = [
	"AGCTCAGGGGCACACCGAACGAAGCCCGG",
	"AAGGCACGGGACAGCGCAACTAGCCCGG",
	"AACTCAGGGGACACCGGAAGAACCCGG"
]

dataset_27 = [
	"CACAGCATGTACACACGAAAACCTCCT",
	"CACAGCTCCATACATCGTACACCCCTT",
	"GCATAGATCTACAGACGAAAACCTCTC"
]

dataset_28 = [
	"TTGTTACGCTTTAAAGAGTCATTTTA",
	"TGGTACTGCTTGAAATAGATCATTTTG",
	"TTGTAGTCTTGAAATAGATCATTTA"
]

dataset_29 = [
	"TCTTAGTTGTTGCCATCCTTTCG",
	"TCATCAGTTGTTGCCATTTTGCTAG",
	"TCATAGGTGTTCCATTCTTTAG"
]

dataset_30 = [
	"AAGCGGATGGCCGTGCTACA",
	"AAGCTTATGGCCGTGCTACA",
	"AACCTCTTGGCTGTACA"
]

dataset_31 = [
	"ATATCGACACGTTTACTTCTTCATACGGG",
	"ATATTGACGCGTTCGAACCCTCAGACCGG",
	"ATATCTAGCCGTTGTGACGTCACACCGG"
]

dataset_32 = [
	"GTCTTTGCGATTAAGATA",
	"GCCTGCGGTGGATTAATACA",
	"GGCTTTGGGTGGATTAAGAGCA"
]

dataset_33 = [
	"GTGATAGGCTGATGACCTTCACCT",
	"GTGATATAGCTGATGTACCTCACCTT",
	"GTTGCTAATCTTGCTGACCTCACCT"
]

dataset_34 = [
	"TTCACTTCTTGTTCGGTAAAG",
	"CTTCACTTCTAGTTCGGTGACAAG",
	"TCTCGCTTCTAGTTCGGATAAG"
]

dataset_35 = [
	"TACTAGCGGTCGTCTGGTTGAAATC",
	"TACTAGGGTCGCCGGGTTGAAATC",
	"TACTAGCGGTTTCGCCGGTCTGACATC"
]

dataset_36 = [
	"CCCAGGCGCACCTGTTCCATTTT",
	"CCGAGTAGACCATGTTCCATTCT",
	"CCCCAGTAGACTTGTTCCATCT"
]

dataset_37 = [
	"GGTCGAATCAGGCTTCTCAGTC",
	"GGGTCGAATCAGGCTTTCAGTC",
	"GGGGTCTGAATCAGGCTTGTCATGTTC"
]

dataset_38 = [
	"ATCGTTGTTCCACCAGCATGTCCGCTT",
	"GATCGACCAATGCATGCGTGCCCT",
	"ATCTGACGATGGCACGCCCGCTT"
]

dataset_39 = [
	"GTAGCCGACCAGACACTCATGATATTTCA",
	"CTAGCCGACCAGAACTCATGATTTTTA",
	"GTCGCCGACCAAACTCGTGGATATTTTCA"
]

dataset_40 = [
	"TTATTCTCTATGGACCGGCTACGTATCCGC",
	"TTATTCTCTATCGACCGTGGTTACATCCGC",
	"TTATCTCTATGCGACCGGCTATTATTCGC"
]

dataset_41 = [
	"CGAACCCCGGTTCTTCGGGCTAAAAGACA",
	"ACTAACCGGTTCTTCGGGCTCAAAGACA",
	"ACCGAACGTGTTCTCGGGCGTAACAGACA"
]

dataset_42 = [
	"CCCGGGTTTGGCGATATGCCTTCGAG",
	"CAGCGGTTAGGCCGGAGCGCCTTCGAG",
	"CAGCGGTTAGGCCGAAATCCTTCGAC"
]

dataset_43 = [
	"GCGATCCTGGATGCCGAGGGCGATG",
	"GTCACCCTGGTGCTCTGAGGCGCGATG",
	"GCGAGCCTGGATGGCCTGAGGGCATG"
]

dataset_44 = [
	"GGCGCCTGGACACACCAGCAGCTTC",
	"GGCGCCTGCACCACCAGCAGCTTC",
	"GGTCGCTGGACACCAGCACTT"
]

dataset_45 = [
	"ACGTGCATCTGTCGATGACGTCGT",
	"ACGTGAATCTTGTCATGCCGTCGT",
	"GTCGTGGCGCATTTTGTCATGACGTCGT"
]

dataset_46 = [
	"GTGGGTTGCTACGCTACGACGTTGCGACG",
	"TACGTTGCTACTGCGTCCGACGTGGCGCG",
	"CGATGTTTGCTCCGCGACGGACGTTGTTCCG"
]

dataset_47 = [
	"CTATAGCCCGTGCACCGTGCCTTAG",
	"CTATAGCCGGTGCTCCGGTCCTTGT",
	"CTTAGCCGGTGTAGCCTCCTTAGT"
]

dataset_48 = [
	"CCCGGACCGGCCGCGTCTGAGGGGGGTG",
	"CGCAGACTGGCCCGCGGCGAGGAGGGTT",
	"CCCAGGCGGGCTCCGCTGCGAGGAGGGT"
]

dataset_49 = [
	"AGGGACCAACTAGCTCCCTATGTGAC",
	"AGGCAGGCCCAATTAGCTCCGTATGTGAC",
	"AAGACAATTAGCTCGGTTTGCGAC"
]

datasets = [
	"dataset_0",
	"dataset_1",
	"dataset_2",
	"dataset_3",
	"dataset_4",
	"dataset_5",
	"dataset_6",
	"dataset_7",
	"dataset_8",
	"dataset_9",
	"dataset_10",
	"dataset_11",
	"dataset_12",
	"dataset_13",
	"dataset_14",
	"dataset_15",
	"dataset_16",
	"dataset_17",
	"dataset_18",
	"dataset_19",
	"dataset_20",
	"dataset_21",
	"dataset_22",
	"dataset_23",
	"dataset_24",
	"dataset_25",
	"dataset_26",
	"dataset_27",
	"dataset_28",
	"dataset_29",
	"dataset_30",
	"dataset_31",
	"dataset_32",
	"dataset_33",
	"dataset_34",
	"dataset_35",
	"dataset_36",
	"dataset_37",
	"dataset_38",
	"dataset_39",
	"dataset_40",
	"dataset_41",
	"dataset_42",
	"dataset_43",
	"dataset_44",
	"dataset_45",
	"dataset_46",
	"dataset_47",
	"dataset_48",
	"dataset_49",
]

file_name = "dataset3"
