dataset_0 = [
    "AACAGGCGCCCCAGGGGTAGGGCCGATGGG",
    "AACAGCCCCCAGGGGTAGGGCCGATGGGG",
    "AACAGCGCCCCAGGGGCTAGGGCCGATGGG",
    "AAAGCGCCCCGGGGGCAGGGCCCTATGGG",
    "ATCTGCCGCCCAGGGGTAGGGCCGATGGG",
    "TACGCGCCCCCCAGCGGTGCGGGCCGCGCGG"]

dataset_1 = [
    "GGTACCAGACTGAGCCGATAATCTCCGCGA",
    "GGTCCCATACTTAGCCGATAATCTCCGCGA",
    "GGTACTATACTGAGCCGATATCTCCCGA",
    "GGTGCCATACTGAGCCGATTATCTCCCGCGT",
    "GGTACATAGTGAGCCGATAGATTTCCGCG",
    "GGTACCATACGAGCTGATAAGTCGCCGCGA"
]

dataset_2 = [
    "TCTTCCTACAGATGGAGGCCTTCCGC",
    "TCGCTGCAGATTTGAGAGCCTTCTGC",
    "GCGCACATATTGAGAGCCTTTGCC",
    "TCCGTACGGATTGAGACTTCCG",
    "CCGCTACAGATTGCAGGCCTTCTGC",
    "TCGCTAGCGATTTGAAGCCTTCTGC"
]

dataset_3 = [
    "TTTCCTGCCAGGTGGAACGC",
    "CTTGCTTGCTCAGGTGGAACGC",
    "TTTGCTGCGTGGGTGGGGACCC",
    "GTTTCCCGCCAGGTTGACCGC",
    "CGTCCTCCAGGTCGAACGC",
    "TTTCCTGCCAGGTGGAACGTC"
]

dataset_4 = [
    "TTCGCTGCAGGTAAGGAGTCGCATC",
    "TTCCGCAGGTGAGGGAGTCCGAG",
    "TTCGCCGCCGGTAAGGAGCCGAC",
    "TTCGCCGCAGGTAAGGGTCCGAAC",
    "TCGCCGCAGGTAAGGGGCTCGATC",
    "TTTCGCCCCAGGTTAGGAGTCCGAAC"
]

dataset_5 = [
    "TCCCCCATTTCAGGTATCGGCTGGTTAAC",
    "TCCCGTTTCCACGTATCGGCTGGTTCC",
    "TCCGCATTTCAGGTCTCGGCGGTGAT",
    "TCCCCATTTCGGGGTCGGCTGGTTAAC",
    "CCCCCATTTCCGGTATCGGCTGGTTAAC",
    "CCCCCATTTCTGCTATCGGCTGGTGAAC"
]

dataset_6 = [
    "CTAGTGCTGGATGGGGTCAGC",
    "CTCAAGTGGTGTATGGGGTCGC",
    "TCTAAGTGGTGTATGGGGGTCCGC",
    "CTATGTTGTGTATGGGGGTTCAGC",
    "CTAAGTGTTTATGGGGGGAGC",
    "CCCAGTGGTGTATGGGGGTCATC"
]

dataset_7 = [
    "ACATCGAATATCTTCTTCATGCCTCTGTG",
    "ACATCCCGAATAGGTTATCCATTGTGGTG",
    "ATCTGGATACCTCATCATGCTGTGTG",
    "ACACCGAATGCTTACCTATGCGGTGTG",
    "ACATCCGTAAGGCTTATTCATGCTGTGTG",
    "ACATCCGAATAGCTTACTCATGCCCGTGTG"
]

dataset_8 = [
    "GAGCGTAGGCCTGGCGTCATCTGGCCA",
    "GAGCGCTAGGGGGTGCCGTCATCTGGCGCA",
    "GAGCGCTAGGTGGCGTCTTCTGGACGC",
    "GAGCGCTAGGGTGGCGTCTCTGGGGA",
    "GAGGCTGAGGGCTCGGCGCAGCTTGGACGCT",
    "GCGCGCTACGGGTGTCTTCATCTCGACGC"
]

dataset_9 = [
    "CCTAGGATGAACCGAGAGGAGA",
    "CCAAGGATCGGACCCAGAGGAGG",
    "CCAAGGATCGTACTCAGAGGCGA",
    "CCAAGGATCTGCACCCAGAGGAGA",
    "GCTAGGATCGAACCCAGAGGAGC",
    "CCAAGGGTCGAACCCGAGTAGGAGA"
]

dataset_10 = [
    "TACATCGGCAACGCCCCTGCAT",
    "TTAGCACGTGCAACAACCCTGCAT",
    "TAGCATCTTGCAACTACTCCTGCAT",
    "TAGCACTCCATACAATCCTGCAT",
    "TCGCACTCGCAACAACCGCTGCAT",
    "AGGACTCGGATCAACTCTTTGCAC"
]

dataset_11 = [
    "ATATTGTACGACGACGTGTTC",
    "ATATTTTTCTACGACTCGTC",
    "ATTATTGTGCTACGACTTGTT",
    "ATAGTGTACTACCACTTGTC",
    "ATATTGTACTACTACTGTC",
    "ATATTGTACGTGCGACTTGTC"
]

dataset_12 = [
    "TGGAACCACAGTCGTGATAA",
    "TCGAACTACAGTCGGTGATAA",
    "TGCGAACTACAGTGCGGTGATAA",
    "GCGTGCACTACAGTCGGTGATAA",
    "TGCGTGCACTACAGTCGGTGAGTTA",
    "TGCCGAATACAGTCGGTGCATA"
]

dataset_13 = [
    "CGTGCCAGGCCTTACTCAAA",
    "CTTGCTAGGCCTCCTCAAA",
    "CGTGCTAGCCTTATTCAAA",
    "TTTGCTAGGTCCTCGCCAAGA",
    "CTCCTAGGCCTTACTCAA",
    "TCTTGCTAGTCTTACTCAAA"
]

dataset_14 = [
    "GATCGTCCATTTTACCTCCCCGTCGT",
    "GATCGTCACTTAACCTCCCGCGTCGT",
    "GATCGGCCATTTGGCCTCCCGCGTCGT",
    "GATCGTCCATTCACCTCCGCGTCGT",
    "GATCGTCCATTTAACCTCCGGCGTCGT",
    "GATCGCCCATTTAACCCCCGCGTCGT"
]

dataset_15 = [
    "CTTCCTCTCGCGCTCCCCCGTA",
    "CCTTCCTTTTGCACCCTCTCGCGTCCA",
    "CCTTCCTTTCCACCGTCTCGTGTA",
    "CCTTCCTTTCGCCCCTCTGCGTA",
    "TCTTCCTTTTGGACCCGCCGCGTA",
    "CCTTCCTTTCCCACCCTCTCGCGTA"
]

dataset_16 = [
    "AGATAACGCTAAGGGTCCAATTG",
    "AGATAATGCAAGGTTCATTGA",
    "AGGTAATGCAAGGGGTCCATTGA",
    "AGATTATGCAGGGTCCAATGA",
    "AGGATAATCCAAGGTTCCATGA",
    "AGATAATGCACGGGTCTCGACGA"
]

dataset_17 = [
    "TGCGCGAACACAACGGTTATCCATACACCC",
    "AGCGGAACACCAGGTTCACCGACACACCC",
    "AGCGCGGACAAGGTCACTCACACAGCC",
    "TAGGGCGAAGACCAAGCACCACGAGCCC",
    "AGCGTAAGACAAGGTCACCCACTCACCG",
    "AGCGCGAAGACCGGTCACCCACACACGC"
]

dataset_18 = [
    "GTCAGAATCTACTAGACTCTGCCT",
    "GTCGTAGCTAATATTCTCGTTCT",
    "GTTCCAGAAGCCAATAGACTCTTCT",
    "GTCAGAAGCTTTTAGACTCTTCG",
    "GGCAGAAGCTAATAGGCTCTTGCT",
    "GGTCAGAACTATAGATTTTGCT"
]

dataset_19 = [
    "CTTGCGTGAGCCTGGTCACAGGTAG",
    "GTTGCGGAGCCTTCGTCTGGAGGGAG",
    "GTTGCGTGAGGCCTGGGTCAGAGGGAG",
    "GTTTCGTAGCCTGTGTCAAGGCAG",
    "GTTGCGTCGGGCCTGCGTGGGGCGAG",
    "GTTCCGTGAGCTCCGTCGGAGGGAG"
]

dataset_20 = [
    "ATGCGGATCTCGGTTACTT",
    "AGTGCGGGATCTCGGTACCC",
    "ACTGCGGAATCTCGGTACCC",
    "ATTGCCGGAATCTCGGTTACCG",
    "ATTGCGGAACTCGGTTCCCC",
    "ATTGCGGGATCTGGTTACCC"
]

dataset_21 = [
    "CACGGTATGCCCATCACGCTCGTGCTATGGT",
    "CACGGTATGGCCATGACGGGCGTGCTAGGT",
    "CACGGTATGCCATGATCGCTCGGGCTAGGT",
    "TCACCGGATGCAACGTCTCGTTGCTAGGT",
    "ACGGCATGCCACGTCGTCGTGCTAGGT",
    "CACGTTGCCATGAGCTCGCGCTAGCT"
]

dataset_22 = [
    "CACACCGAAAGTTGTATTCGCGGGTACA",
    "CATACCGAAAGTTGTGGTCGCGTTGTA",
    "TACACCTAGAGTGTATTCGCGTGTATA",
    "CCACAGCCGAAAGGTGCATTCGCGTGTATA",
    "CACAGCGTAAGTTGGTATTCGCGTGTATA",
    "ACACCGAAAGTTGATTCTCGTGTATA"
]

dataset_23 = [
    "TCTACTCTAAATGTTTTATGGGCCGAATGT",
    "TCTCGGCAAATGTTTTATGGGCGAATGT",
    "TCTAGGTCAAATGTCGCGTACGGGCGAAGT",
    "CTAGTCAAACGTTTTTATGGGCGAAGT",
    "TCGTAGTCACATCTTTTATGGGCGGAGT",
    "TCTGGTCTATGTTTTATGGTCGAAGT"
]

dataset_24 = [
    "GGTTGCTGGCGGGGATTGCATT",
    "GGGTGCCTGCGAGATTTCATT",
    "GGGTGCTTGGGAGAGTGCAT",
    "GCGTGCTTGCACATCTCAGT",
    "GGGTGGCTTGCGAGATGCATT",
    "GGGTGCTTGCTGAGATTGCATT"
]

datasets = [
    "dataset_0",
    "dataset_1",
    "dataset_2",
    "dataset_3",
    "dataset_4",
    "dataset_5",
    "dataset_6",
    "dataset_7",
    "dataset_8",
    "dataset_9",
    "dataset_10",
    "dataset_11",
    "dataset_12",
    "dataset_13",
    "dataset_14",
    "dataset_15",
    "dataset_16",
    "dataset_17",
    "dataset_18",
    "dataset_19",
    "dataset_20",
    "dataset_21",
    "dataset_22",
    "dataset_23",
    "dataset_24",
]

file_name = "dataset6"
